export const colors = {
    primary: '#A52A2A',
    white:'white',
    black:'black',
    gray: 'gray',
    lightgray: 'lightgray',
    darkgray: 'darkgray',
    red: 'red',
    green: 'green',
    yellow: '#FEBE10',
    desc: '#708090',
    borderClr : '#ccc',
    purple: 'purple',
    modalBackground: 'rgba(0, 0, 0, 0.5)',
    searchbar : '#e4e4e4',
    orange: '#FFA07A',
    redTitle : '#FF0800',
    blackBackground : '#343434',
}