export const strings = {
    error_checking_saved_news : 'Error checking saved news:',
    remove_news : 'Removed, This news has been removed from saved items.',
    save_news : 'Saved, This news has been saved.',
    error_saving_removing_news: 'Error saving/removing news:',
    source : 'Source: ',
    dummy: 'Tempor reprehenderit duis quis excepteur aliquip ut id exercitation consectetur. Culpa ex est non cillum. Proident quis dolor ullamco nulla ex in cillum. Nulla magna incididunt in et minim proident ea. Ut elit adipisicing sunt velit. Irure anim quis aute aliquip dolor elit voluptate. Est laborum exercitation officia dolore. Velit velit Lorem veniam nulla. Reprehenderit ad aliqua in incididunt occaecat ut aliqua. Mollit dolor ad pariatur enim. Excepteur veniam mollit pariatur veniam. Quis sunt in enim commodo proident tempor exercitation excepteur est. Occaecat id veniam est officia laboris. Nostrud officia proident laboris reprehenderit excepteur qui eiusmod aliquip. Sint ad anim ex anim mollit. Veniam sunt aliqua fugiat est enim. Ipsum officia commodo magna commodo id eiusmod. Anim quis pariatur cupidatat proident irure dolor ad eu. Laborum est veniam officia ipsum. Culpa eu est officia eiusmod nostrud exercitation anim sint. Est velit aliqua sint aute enim reprehenderit.',
    keywords : 'Keywords: ',
    no_keywords_available : 'No keywords available',
    published_on : 'Published on: ',
    modal_title_remove_news : 'Are you sure you want to remove this news?',
    modal_title_save_news : 'Are you sure you want to save this news?',
    modal_desc_remove_news : 'You will no longer get this news.',
    modal_desc_save_news : 'You can see it on saved tab.',
    categories : 'Categories',
    countries : 'Countries',
    search : 'Search',
    feedback_submitted : 'Feedback Submitted',
    send_us_your_feedback : 'Send Us Your Feedback',
    your_feedback: 'Your Feedback: ',
    submit_feedback : 'Submit Feedback',
    type_your_feedback : "Type your feedback here...",
    enter_email : 'Please enter your email address',
    reset_email_send : 'Password reset email sent!, Please check your email.',
    reset_password : 'Reset Password',
    reset_pass_link_send : 'A reset password link will be sent on this email.',
    email_address : 'Email Address',
    sending : 'Sending...',
    send_password_reset_email : 'Send Password Reset Email',
    error: 'error',
    signin: 'Signin',
    already_have_account : 'Already have an account?',
    continue_with_email : 'Continue with Email',
    continue_with_google : 'Continue with Google',
    continue_with_phone : 'Continue with Phone',
    news : 'NEWS',
    n_e_w_s : 'North-East-West-South',
    signin_with_google : 'Signed in with Google',
    google_signin_failed : 'Google Sign-In Failed',
    send_OTP : 'Send OTP',
    log_in: 'Logged in',
    invalid_code : 'Invalid code.',
    privacy_policy_for_newzz_app : 'Privacy Policy for Newzz App',
    effective_date: 'Effective Date: [November 25, 2024]',
    privacy_desc_1 : 'Welcome to Newzz. This Privacy Policy outlines how we collect, use, and protect your personal information when you use our app. By using our app, you agree to the collection and use of information in accordance with this policy.',
    privacy_desc_2 : `- Personal Information: We may collect personal information such as your name, email address, and location when you register or subscribe to our services.${'\n'}- Usage Data: We collect information about how you access and use the app, including your device information, IP address, and browsing patterns.`,
    privacy_desc_3 : `We use the information we collect for various purposes, including:${'\n'}- To provide and maintain our services.${'\n'}- To notify you about changes to our app.${'\n'}- To allow you to participate in interactive features when you choose to do so.${'\n'}- To provide customer support.${'\n'}- To gather analysis or valuable information so that we can improve our app.${'\n'}- To monitor the usage of our app.${'\n'}- To detect, prevent, and address technical issues.`,
    privacy_desc_4 : `We do not sell or rent your personal information to third parties. We may share your information in the following situations:${'\n'}- With service providers to monitor and analyze the use of our app.${'\n'}- To comply with legal obligations or protect and defend our rights.`,
    privacy_desc_5 : `The security of your data is important to us, and we strive to use commercially acceptable means to protect your personal information. However, no method of transmission over the internet or method of electronic storage is 100% secure.`, 
    privacy_desc_6 : `You have the right to:${'\n'}- Access, update, or delete the information we have on you.${'\n'}- Withdraw your consent at any time where we rely on your consent to process your personal information.${'\n'}- Request that we restrict the processing of your personal information.`,
    privacy_desc_7 : `We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.`,
    privacy_desc_8 : `If you have any questions about this Privacy Policy, please contact us:${'\n'}- Email: [aryan.saxena@appinventiv.com]${'\n'}- Address: [Appinventiv Technologies Pvt. Ltd, Noida-201301]`,
    privacy_title_1 : '1. Introduction',
    privacy_title_2 : '2. Information We Collect',
    privacy_title_3 : '3. How We Use Your Information',
    privacy_title_4 : '4. Sharing Your Information',
    privacy_title_5 : '5. Data Security',
    privacy_title_6 : '6. Your Rights',
    privacy_title_7 : '7. Changes to This Privacy Policy',
    privacy_title_8 : '8. Contact Us',
    choose_from_gallery : 'Choose from Gallery',
    open_camera : 'Open Camera',
    password_caution : 'Password should be at least 6 characters.',
    username_caution : 'Username should be at least 5 characters long.',
    change : 'Change',
    enter_new_password : 'Enter new Password',
    enter_new_username : 'Enter new username',
    change_password : 'Change Password',
    change_username : 'Change Username',
    no_username : 'No Username',
    change_profile_pic : 'Change Profile Picture',
    dummy_pass : '********',
    username_updated_successfully : 'Username updated successfully',
    password_updated_successfully : 'Password updated successfully',
    error_updating_password : 'Error updating password',
    error_updating_username : 'Error updating username',
    back_to_home : 'Back to Home',
    terms_of_use : 'Terms of Use for Newzz App',
    terms_title_1 : '1. Acceptance of Terms',
    terms_title_2 : '2. Changes to Terms',
    terms_title_3 : '3. User Responsibilities',
    terms_title_4 : '4. Intellectual Property',
    terms_title_5 : '5. Limitation of Liability',
    terms_title_6 : '6. Governing Law',
    terms_title_7 : '7. Contact Us',
    terms_desc_1 : 'By accessing or using [Newzz App], you agree to comply with and be bound by these Terms of Use. If you do not agree with any part of these terms, you must not use our app.',
    terms_desc_2 : 'We reserve the right to modify these Terms of Use at any time. Any changes will be effective immediately upon posting the revised terms in the app. Your continued use of the app after changes are made constitutes your acceptance of the new terms.',
    terms_desc_3 : `You agree to use [Newzz App] only for lawful purposes and in a manner that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the app.`,
    terms_desc_4 : `All content, trademarks, and other intellectual property rights in [Newzz App] are owned by us or our licensors. You may not reproduce, distribute, or create derivative works from any content without our express written permission.`,
    terms_desc_5 : `To the fullest extent permitted by law, we shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of [Newzz App].`,
    terms_desc_6 : `These Terms of Use shall be governed by and construed in accordance with the laws of India. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in [Your Jurisdiction].`,
    terms_desc_7 : `If you have any questions about these Terms of Use, please contact us:${'\n'}- Email: [aryan.saxena@appinventiv.com]${'\n'}- Address: [Appinventiv Technologies Pvt. Ltd, Noida-201301]`,
    remove_img : 'Remove Profile Picture',
    no_news_to_show : 'No news to show.',
    title_logout : 'Are you sure you want to logout?',
    desc_logout: 'You will be redirected to the Signin screen.',
    remove_pic_title : 'Remove Profile Picture?',
    remove_pic_desc : 'Are you sure you want to remove profile picture?',
    go_to_home : 'Go to Home Screen',
    stay_updated : 'Stay Updated!',
    get_breaking_news : 'Get breaking news and personalized updated directly to your feed.',
    forgot_pass : 'Forgot Password?',
    login : 'Login',
    password : 'Password',
    login_pass_error : 'Please Enter Password with 6 or more characters',
    login_email_error1 : 'Email cannot be empty',
    login_email_error2: 'Please Enter Valid Email',
    email_not_verified: 'Email not verified',
    verify_email : 'Please verify your email before logging in. Check your inbox for the verification link.',
    resend_email : 'Resend Email',
    ok : 'OK',
    email_pass_not_matched : 'Email or Password does not match!',
    create_account : 'Create an Account',
    
}  