export const images = {
    splash_gif :require('./images/global-news.gif'),
    tutorial: require('./images/tutorial.jpg'),
    appLogo: require('./images/appLogo.png'),
    mail: require('./images/mail.png'),
    google: require('./images/google.png'),
    otp: require('./images/otp.png'),
    password: require('./images/padlock.png'),
    hide: require('./images/hide.png'),
    view: require('./images/view.png'),
    back : require('./images/left-arrow.png'),
    home: require('./images/home.png'),
    home1: require('./images/home1.png'),
    discover: require('./images/loupe.png'),
    discover1: require('./images/loupe1.png'),
    settings: require('./images/settings.png'),
    settings1: require('./images/settings.png'),
    saved: require('./images/saved.png'),
    saved1: require('./images/saved1.png'),
    profile: require('./images/profile.png'),
    bell: require('./images/bell.png'),
    search: require('./images/magnifying-glass.png'),
    like: require('./images/heart.png'),
    goback: require('./images/back.png'),
    checked : require('./images/checked.png'),
    next: require('./images/next.png'),
    logout: require('./images/logout.png'),
}

export const fallback = require('./images/tutorial.jpg');